### ISSUE TITLE
how to get private key from 12 word seed

### ISSUE THREAD

**Issue by gaoyang1120** [kadena-io/chainweaver#355]
I use mac wallet chainweaver , get a address from Receive button, i send my kda to account name ,i can't see balance

**Comment by gaoyang1120** [comment]
how to get balance on my address as the account

**Comment by gaoyang1120** [comment]
my address is : c79daf8bbfb1c37855f34098b3f4ed8ad3d8468a889cf3326a43d38a470e40dc|0|eQpjNzlkYWY4YmJmYjFjMzc4NTVmMzQwOThiM2Y0ZWQ4YWQzZDg0NjhhODg5Y2YzMzI2YTQzZDM4YTQ3MGU0MGRjCjAKMzI3NTE4YzY=

**Comment by gaoyang1120** [comment]
a6e0c268c5a86acc3744be537c413d5d3fe7664747e1a7566fbcdd62c822ffc0|0|783761a6

**Comment by mightybyte** [comment]
Chainweaver intentionally does not expose your private keys.  You can check the latest balances in your wallet by clicking "Refresh" on the wallet screen (make sure you have selected "Mainnet" as your network).

You can also check your balance but putting your public key in https://balance.chainweb.com/.  You can get the public key by clicking the `...` button on the far right hand side of the account table.

If you need more help, it will be easier for people to answer these kinds of questions on our Discord.
