### ISSUE TITLE
Mainnet not connecting

### ISSUE THREAD

**Issue by jadeye** [kadena-io/chainweaver#642]
My balance doesn't display and Mainnet shows red dot next to it.
Why is that??

![Selection_244](https://user-images.githubusercontent.com/1064541/115558715-ad98fa00-a2bb-11eb-8935-f1d8f8266abc.png)

**Comment by mightybyte** [comment]
There was a recent change in the way the bootstrap node infrastructure is organized.  You can fix this by removing all those nodes and replacing them with a single `api.chainweb.com` (and `api.testnet.chainweb.com` for testnet).

**Comment by jadeye** [comment]
Thank you very much, that was helpful.

**Comment by jmininger** [comment]
2.2.0 has been released. This issue should be fixed, so im closing this. Feel free to reopen if the issue persists
