### ISSUE TITLE
cryptonite causes runtime errors on certain older cpus

### ISSUE THREAD

**Issue by jmininger** [kadena-io/chainweaver#645]
A user recently reported running the chainweaver setup workflow and ran into a runtime error:
```
Illegal instruction (core dumped)... (9 KB left)
```
An investigation led me to: https://github.com/NixOS/nixpkgs/issues/81915 and https://github.com/haskell-crypto/cryptonite/issues/314

We confirmed that the cpu he is using matches the one mentioned in the second issue. I am creating this issue so that it is documented in case anyone runs into the same issue.

**Comment by mightybyte** [comment]
Thanks for doing the research on this.  I ran into this issue awhile back as well.  At the moment I can't see this making it high enough on the priority list for us to spend time on, so I'm closing for now.  Although I certainly wouldn't object to merging an appropriate fix if someone really wanted to work on it.
