### ISSUE TITLE
Add support for gas station

### ISSUE THREAD

**Issue by Thanos420NoScope** [kadena-io/chainweaver#652]
Chainweaver could look up the receiving account balance and enter the public gas station if its empty or doesnt exist
![image](https://user-images.githubusercontent.com/6309193/119244918-1be30d80-bb43-11eb-99a3-648c6fde7af2.png)
Could also be entered by default on crosschains to simplify

**Comment by jmininger** [comment]
2.2.0 has been released. This issue should be fixed, so im closing this. Feel free to reopen if the issue persists
