### ISSUE TITLE
(Minor) Destination Chain ID drop-down menu to deploy contract is in alphebetical, not numerical order

### ISSUE THREAD

**Issue by mat888** [kadena-io/chainweaver#667]
kadena-chainweaver-linux-2.1.1.deb

When deploying a contract and choosing which Chain ID to deploy to, the chains are listed in alphabetized order (0, 1, 10, 11, 12...) rather than numerical. Come a time when more chains are deployed, this will get progressively more annoying.

**Comment by jmininger** [comment]
Addressed in #709 , will be in next release
