### ISSUE TITLE
Trying to initiate cross chain transfer to an account with module as guard keeps trying to load keyset

### ISSUE THREAD

**Issue by floordebest** [kadena-io/chainweaver#670]
When trying to make a cross chain transfer to an account that doesn't have a keyset as guard and balance of 0.0 (in my case a gaspayer account that has a gasstation module as guard) the pop up shows "Querying keysets..." and all buttons are unresponsive, clicking outside the popup wont close it.

sender, chain 0 (testnet): fw-gaspayer (keyset as guard)
receiver, chain 1 gaspayer account (testnet): fw-gaspayer-v2
Gasstation module: free.floppie-wallet-gas-station

**Comment by floordebest** [comment]
Running on Macbook Pro / MacOs Big Sur 11.5 / Chainweaver 2.1.1

**Comment by jmininger** [comment]
I think this an incomplete pattern match on guard type that snuck in. I ran across it the other day. Should be fixed in the next release. Thank you for raising it.

**Comment by jmininger** [comment]
2.2.0 has been released. This issue should be fixed, so im closing this. Feel free to reopen if the issue persists
