### ISSUE TITLE
Module Explorer fails to load pact 4 syntax modules

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweaver#672]
Steps to reproduce.

1. Open chainweaver
2. Go to the module explore
3. Search for the module relay.pool
4. Select View

Expected result:
The pact source code is shown.

Actual result:
"loading of module failed: Compilation failed: util.guards: Failure: Syntax error: Expected: time, Expected: list, Expected: literal"

**Comment by jmininger** [comment]
Fixed in #659 and will be available in Chainweaver 2.2

**Comment by trendzetter** [comment]
super! I am testing the RC now. I tried some workarounds to make the ubuntu build work. Provided feedback here: #677
