### ISSUE TITLE
2.2RC Cross-chain transfer fails on 'Gas Limit must be smaller than or equal to 400' while gas limit was set to default 400

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweaver#678]
Scenario:
1. Log on to chainweaver
2. Create a cross-chain transfer to create a new account (non-existing). Leave all options default (free-gas-station, gas limit=400)
3. The preview shows no errors.

Expected result:
All the steps finish successfully and the transfer finishes successfully.

Actual result:
´´´
NetworkError_Status (Status {statusCode = 400, statusMessage = "Bad Request"}) "\"Validation failed for hash \\\"0YlwB06GDLo2BF7glmEtoTFG62YJvoPVPMiTRZL-ncg\\\": Attempt to buy gas failed with: (enforce (<= (chain-gas-limit)...: Failure: Tx Failed: Gas Limit must be smaller than or equal to 400\""
´´´

**Comment by trendzetter** [comment]
I did several and I could finish them with the cross-chain transfer finish tool.
I am creating my accounts on all chains now and it happens every time:

![Schermafdruk van 2021-08-21 20-19-18](https://user-images.githubusercontent.com/6834530/130331456-927cf681-1be6-4883-bed1-485ae72b07cd.png)

**Comment by jmininger** [comment]
2.2.0 has been released. This issue should be fixed, so im closing this. Feel free to reopen if the issue persists
