### ISSUE TITLE
Cross chain transfer fails with placeholder error message. ("blah")

### ISSUE THREAD

**Issue by mat888** [kadena-io/chainweaver#679]
Here is my attempt at a cross chain transfer on  testnet.

![image](https://user-images.githubusercontent.com/22969119/130521004-67b181ba-9cb3-4def-bd5d-81bd75d4b706.png)

After a bit of time.

![image](https://user-images.githubusercontent.com/22969119/130521063-31a569d9-fae3-483a-99f8-3cd426fbaef5.png)

The funds never came though and the original account has no less coins. I'm pretty sure my mistake was not having any coins on the receiving chain to pay gas, but the user messaging should be clear.

**Comment by jmininger** [comment]
Thank you for reporting this issue. This was fixed a few months ago in #654 and will be a part of the 2.2 release

**Comment by jmininger** [comment]
2.2.0 has been released. This issue should be fixed, so im closing this. Feel free to reopen if the issue persists
