### ISSUE TITLE
Protecting against high-frequency griefing attack 

### ISSUE THREAD

**Issue by tbenst** [kadena-io/chainweaver#706]
I’ve witnessed a high-frequency griefing attack performed by pub key: 48e1abd29d6e230c8640e53af55ba5f3ca87d6e9d4dd72870cb599542faf32f6

The attack goes like this:

Alice has 10 KDA in an account, and wants to send Bob 1 KDA. Bob creates a new pub & private key, and securely sends pub key to Alice. Alice initiates a safe transfer from her account to an account named after Bob’s pub key. Eve intercepts the broadcast transaction that has yet to be included in a block, and quickly creates an account with the name of Bob’s pub key, but with an “any” key predicate that includes both Bob’s and Eve’s pub key. If Eve manages to get her transaction into a block before Alice’s transaction goes through, then the 1 KDA may end up in an account that Eve has access to, and Eve quickly drains the account before Alice or Bob can react.

Does this use of “any” predicate allow for funds to be stolen from a Safe Transfer?

Perhaps it’s time to add easy functionality to reserve an account on all chains?

I understand that k accounts solve this issue, but that still leaves most of the namespace suspect to this annoying attack. It’s a tricky problem but perhaps there’s a proof of work solution—requiring a certain hash difficulty for account creation would at least make spamming accounts more expensive.

**Comment by mightybyte** [comment]
This attack will not work if Alice uses `transfer-create`.  In order for the attack to work, the account has to NOT exist already.  If the account doesn't exist, Alice MUST use `transfer-create`.  If Eve front-runs the account creation with a different keyset, the `transfer-create` will fail and no funds will be sent to the attacker.

But yes, `k:` accounts are the way to reserve an account on all chains without even needing to send any transactions.  Just put `k:` at the beginning of your account name and you're good to go.
