### ISSUE TITLE
Poor UX: default gas price lower than the minimum gas price causes transactions to fail

### ISSUE THREAD

**Issue by dandv** [kadena-io/chainweaver#713]
In [this YouTube video](https://www.youtube.com/watch?v=I3BEUqRfr78&t=434s), a crypto influencer shows how his first transaction failed because the default gas price was lower than the minimum gas price.

This poor first impression could be easily avoided by setting the default gas price to at least the minimum gas price.

![image](https://user-images.githubusercontent.com/33569/146570901-b4178107-19df-4d92-a7fb-036aae71fe7d.png)

**Comment by jmininger** [comment]
Default fixed in the newest release.
