### ISSUE TITLE
cannot transfer crosschain tokens that only implement fungible-v2

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweaver#771]
![unknown](https://user-images.githubusercontent.com/6834530/168154158-f7f561ef-124c-4a6e-a585-8cbb011e7503.png)

**Comment by jmininger** [comment]
This is intentional. We encourage all tokens to upgrade their contract to implement the fungible-xchain-v1 interface

**Comment by trendzetter** [comment]
Is it somewhere written that fungible-v2 is deprecated?
